# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "flutter_mobile" ]
  pull_request:
    branches: [ "flutter_mobile" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Setup Flutter SDK
        # You may pin to the exact commit or the version.
        # uses: flutter-actions/setup-flutter@74fc21b209e70873f3caff52c4caf25d862f2a39
        uses: flutter-actions/setup-flutter@v2.2
        with:
          # The version to install: Default: 3.0.2
          version: 3.0.2 # optional, default is 3.0.2
          # The version to install. Default: stable
          channel: stable # optional, default is stable
          # Cache the installed Flutter SDK. Default: false
          cache: false # optional, default is false
          # An explicit key for restoring and saving the Flutter SDK to/from cache
          cache-key: flutter # optional, default is flutter

      - name: Install dependencies
        run: flutter pub get

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: dart analyze

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      - name: Run tests
        run: flutter test
